configuration:
  projectName: Service-0
server:
  port: 9000
service1:
  host: 192.168.1.41
  port: 9001
---
spring:
  profiles: development
server:
  port: 9000
service1:
  host: localhost
  port: 9001
